DO NOT MERGE - Migrate to core24 and gnome-46-2404
canonical/firefox-snap pull request #65
Opened 2024-07-09 12:42 UTC by bandali0

This PR switches Firefox stable snap from core22 and gnome-42-2204 to core24 and gnome-46-2404.

This **must not be merged** yet, given there are a number of outstanding issues with the new stack as well as currently missing armhf builds, and that we should do the switch for Nightly and Beta first, and give advance heads up about the change on the Ubuntu Community Hub (Discourse) as we did for the switch to core22.

However, in the mean time, builds for this branch are available from the `latest/candidate/core24` channel of the `firefox` snap on the snap store for testing purposes.

2024-07-15 13:31 UTC, seb128 commented
Thanks, any reason to not have started with nightly which we could probably merge earlier?

2025-06-14 13:24 UTC, tsteven4 commented
The content for /usr/share/libdrm has moved from gnome-platform to gpu-2404, thus the layout needs to change from

>  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm

to 
 > /usr/share/libdrm:
     bind: $SNAP/gpu-2404/libdrm

This can be seen searching for amdgpu.ids:
$ find $SNAP -name amdgpu.ids
/snap/firefox/6231/gpu-2404/libdrm/amdgpu.ids

2025-06-16 11:51 UTC, tsteven4 commented
The fix for /usr/share/libdrm is more complicated, see #133, #134.

2025-09-20 09:22 UTC, brlin-tw commented
Hello, are there any blockers currently preventing the change from landing on the stable branch?  If so, do you have any tips on where one can locate them?

2025-09-22 07:15 UTC, nteodosio commented
Hi, yes: https://launchpad.net/bugs/2043993.

Am 20/09/2025 um 02:23 schrieb ***@***.***:
> brlin-tw left a comment (canonical/firefox-snap#65)
> 
> Hello, are there any blockers currently preventing the change from landing on
> the stable branch?  If so, do you have any tips on where one can locate them?
>

2025-09-22 08:11 UTC, brlin-tw commented
@nteodosio 

Thanks for the information!

2025-10-21 08:20 UTC, kabinbr1 commented
without this firefox uses llvmpipe instead of radeonsi and makes opengl performance in a RX 9060 completely awful

2025-11-09 20:42 UTC, aleasto requested changes

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
>        - mesa-vulkan-drivers
Drop: these are provided by `mesa-2404:gpu-2404`

Also drop:
```
      # update the path to the vulkan drivers for the snap environment
      sed -i 's#/usr/lib/#/snap/firefox/current/usr/lib/#' $CRAFT_PART_INSTALL/usr/share/vulkan/icd.d/*.json
```
from `override-build`

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
>        - usr/share/vulkan
Drop together with `mesa-vulkan-drivers`

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
>        - data-dir/themes
Drop all of this

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
>        - libvulkan1
Drop: this is provided by `mesa-2404:gpu-2404`

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
> +      mkdir $CRAFT_PART_INSTALL/{gpu-2404,data-dir,data-dir/{icons,sounds,themes}}
`gnome-platform` is still a used mountpoint, so removing it doesn't make much sense to me, unless the mentioned snapd bug is already fixed.

Since practice shows that snapd is able to mount the `gnome-46-2404` contents in `$SNAP/gnome-platform` even without it being listed here, I believe we can drop this workaround entirely.   _(unless adding `gnome-platform` again here would help with [bug 2043993](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2016358)?)_

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
> +        - libvpl2
All of these are included in `gnome-46-2404`

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
>        - libspa-0.2-modules
Drop: These are provided by `gnome-46-2404`

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
>        - pipewire-pulse
Why are these installed?

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
> +      - libcurl4t64
Drop: These are provided by `gnome-46-2404`

2025-11-09 20:42 UTC, aleasto commented on snapcraft.yaml
> +      - libxt6t64
Drop: this is provided by `gnome-46-2404`

2026-04-07 07:18 UTC, closed without merging