Add LIBTHAI_DICTDIR environment
canonical/firefox-snap pull request #9
Opened 2022-10-24 07:45 UTC by wannaphong

From https://forum.snapcraft.io/t/thai-word-breaking-doesnt-work-in-snaps-using-common-gnome-snaps-e-g-firefox/32303, I found the firefox snap don't has LIBTHAI_DICTDIR environment.

2023-05-17 16:02 UTC, lissyx commented
@seb128 @bandali0 any reason this was not merged? It looks like to be the fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1796939

2023-05-17 16:07 UTC, lissyx commented
also there's mention on the thread that one should expose that in the `desktop-launch` script from gnome platform but as usual I am unable to find where it lives.

2023-05-22 21:35 UTC, seb128 requested changes

2023-05-22 21:35 UTC, seb128 commented on snapcraft.yaml
> +      LIBTHAI_DICTDIR: "$SNAP/usr/share/libthai/"
Shouldn't that be $SNAP/gnome-platform/usr/share/libthai instead?

2023-05-22 21:38 UTC, seb128 commented
> also there's mention on the thread that one should expose that in the `desktop-launch` script from gnome platform but as usual I am unable to find where it lives.

the export should probably be added to https://github.com/snapcore/snapcraft/blob/main/extensions/desktop/common/desktop-exports instead of firefox indeed

2023-05-23 06:54 UTC, lissyx commented
I dont have the credentials to close this PR, but I submitted https://github.com/snapcore/snapcraft/pull/4170

2023-05-24 08:01 UTC, seb128 commented
Closing this one since the issue is getting fixed in the desktop script which is going to resolve the problem for firefox as well as for other snaps

2023-05-24 08:01 UTC, closed without merging